import { FileIcon } from '../../../shared/components/icons/Icons'
import { formatFileSize, getFileExtension } from '../../../shared/utils/file'
import type { ConversionJob } from '../types'
import { eyebrow } from '../../../shared/styles'

export function JobProgress({ file, job }: { file: File | null; job: ConversionJob }) {
  const progress = Math.max(job.status === 'QUEUED' ? 4 : 8, Math.min(99, job.progress))
  const filename = file?.name || job.input_filename
  return <section className="mx-auto max-w-[590px] px-5 pb-7 pt-[42px] text-center"><div className="relative mx-auto mb-[26px] size-28" role="progressbar" aria-label="Conversion progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><svg className="w-full -rotate-90 [&_circle]:fill-none [&_circle]:stroke-[var(--surface-strong)] [&_circle]:stroke-[7]" viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52" /><circle className="stroke-[var(--accent-strong)] [stroke-dasharray:327] [stroke-linecap:round] transition-[stroke-dashoffset] duration-200" cx="60" cy="60" r="52" strokeDashoffset={327 - (327 * progress) / 100} /></svg><div className="absolute inset-0 flex items-center justify-center"><strong className="text-2xl">{progress}</strong><span className="text-[10px] text-[var(--muted)]">%</span></div></div><p className={eyebrow}>{job.status === 'QUEUED' ? 'Waiting for a worker' : 'Conversion in progress'}</p><h2 className="m-0 text-[31px] tracking-[-.04em]" id="conversion-title">{job.status === 'QUEUED' ? 'Your file is queued' : 'Converting your file'}</h2><p className="text-xs leading-relaxed text-[var(--muted)]">Job {job.id.slice(0, 8)} · This page updates automatically.</p><div className="mt-6 flex items-center rounded-[14px] bg-[var(--surface)] p-[13px] text-left"><div className="grid size-[38px] place-items-center rounded-[11px] bg-[var(--surface-soft)] text-[var(--accent-strong)] [&_svg]:w-[18px]"><FileIcon /></div><span className="ml-[11px] min-w-0 flex-1"><strong className="block overflow-hidden text-ellipsis whitespace-nowrap text-[11px]" title={filename}>{filename}</strong><small className="mt-[3px] block overflow-hidden text-ellipsis whitespace-nowrap text-[9px] text-[var(--muted)]">{file ? `${getFileExtension(file)} · ${formatFileSize(file.size)}` : 'Stored in backend'}</small></span><i className="size-2 animate-pulse rounded-full bg-[var(--accent-strong)]" aria-hidden="true" /></div></section>
}
