import { FileIcon } from '../../../shared/components/icons/Icons'
import { formatFileSize, getFileExtension } from '../../../shared/utils/file'
import type { ConversionJob } from '../types'

export function JobProgress({ file, job }: { file: File | null; job: ConversionJob }) {
  const progress = Math.max(job.status === 'QUEUED' ? 4 : 8, Math.min(99, job.progress))
  const filename = file?.name || job.input_filename
  return <section className="w-full max-w-xl rounded-3xl border border-slate-200 bg-white p-14 text-center shadow-[0_24px_64px_rgba(15,23,42,.09)] max-sm:rounded-2xl max-sm:p-6"><div className="relative mx-auto mb-8 size-30" role="progressbar" aria-label="Conversion progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><svg className="size-full -rotate-90" viewBox="0 0 120 120" aria-hidden="true"><circle className="fill-none stroke-blue-100 stroke-[7]" cx="60" cy="60" r="52" /><circle className="fill-none stroke-blue-600 stroke-[7] [stroke-dasharray:327] [stroke-linecap:round] transition-[stroke-dashoffset] duration-100" cx="60" cy="60" r="52" strokeDashoffset={327 - (327 * progress) / 100} /></svg><div className="absolute inset-0 flex items-center justify-center pt-1"><strong className="text-2xl tracking-tight text-slate-900">{progress}</strong><span className="ml-0.5 text-xs font-bold text-slate-500">%</span></div></div><div><span className="mb-3 block text-xs font-extrabold tracking-[.14em] text-blue-600">{job.status === 'QUEUED' ? 'WAITING FOR A WORKER' : 'CONVERSION IN PROGRESS'}</span><h1 className="text-4xl font-bold tracking-[-.045em] text-slate-900 max-sm:text-3xl" id="conversion-title">{job.status === 'QUEUED' ? 'Your file is queued' : 'Converting your file'}</h1><p className="mx-auto mt-3 max-w-md text-base leading-7 text-slate-500">Job {job.id.slice(0, 8)} · You can keep this window open while the backend processes it.</p></div><div className="mt-8 flex items-center rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left"><div className="mr-3 grid size-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><FileIcon className="size-5 fill-none stroke-current stroke-[1.7]" /></div><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-900" title={filename}>{filename}</strong><span className="mt-1 block text-xs text-slate-500">{file ? `${getFileExtension(file)} · ${formatFileSize(file.size)}` : 'Stored in backend'}</span></div><span className="ml-3 size-2.5 animate-pulse rounded-full bg-blue-600" aria-hidden="true" /></div></section>
}
