import { Alert } from '../../../shared/components/ui/Alert'
import { CheckIcon, DownloadIcon, FileIcon } from '../../../shared/components/icons/Icons'
import { getConvertedFileName } from '../../../shared/utils/file'
import type { ConversionTool } from '../../tools/types'
import type { ConversionJob } from '../types'

type Props = { file: File | null; tool: ConversionTool; job: ConversionJob; error: string | null; onDownload: () => void; onRestart: () => void }

export function ResultCard({ file, tool, job, error, onDownload, onRestart }: Props) {
  const filename = job.output_filename || getConvertedFileName(file?.name || job.input_filename, tool.outputSuffix.slice(1))
  return <section className="w-full max-w-xl rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-[0_24px_70px_rgba(15,23,42,0.09)] sm:p-12"><div className="mx-auto mb-7 grid size-20 place-items-center rounded-full bg-emerald-50 text-emerald-600 ring-8 ring-emerald-50/60 [&_svg]:size-9"><CheckIcon /></div><div><span className="text-xs font-bold tracking-[0.2em] text-emerald-600">CONVERSION COMPLETE</span><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl" id="result-title">Your file is ready</h1><p className="mx-auto mt-3 max-w-md leading-7 text-slate-500">The file was converted successfully and is ready to download.</p></div><div className="mt-8 flex items-center gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left"><div className="grid size-12 shrink-0 place-items-center rounded-xl bg-blue-600 text-white [&_svg]:size-6"><FileIcon /></div><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-900" title={filename}>{filename}</strong><span className="mt-1 flex items-center gap-2 text-xs font-medium text-slate-500">{tool.outputSuffix.slice(1).toUpperCase()} <i className="size-1 rounded-full bg-slate-300" /> Backend output</span></div><span className="hidden items-center gap-1 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700 sm:flex [&_svg]:size-3.5"><CheckIcon /> Ready</span></div><div className="mt-7 grid gap-3">{error && <Alert>{error}</Alert>}<button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 font-bold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 [&_svg]:size-5" type="button" onClick={onDownload}><DownloadIcon />Download file</button><button className="min-h-12 rounded-xl border border-slate-300 bg-white px-5 font-bold text-slate-700 transition hover:border-slate-400 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600" type="button" onClick={onRestart}>Convert another file</button></div></section>
}
