"""Generate frontend and SDK artifacts from plugin manifests."""

from __future__ import annotations

import argparse
import importlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from plugins.base import PluginManifest
from plugins.catalog import build_tool_catalog


def manifests() -> list[PluginManifest]:
    result: list[PluginManifest] = []
    for path in sorted((ROOT / "plugins").rglob("manifest.py")):
        relative = path.parent.relative_to(ROOT)
        if any(part.startswith("_") for part in relative.parts):
            continue
        module = ".".join((*relative.parts, "manifest"))
        manifest: PluginManifest = importlib.import_module(module).MANIFEST
        manifest.validate()
        result.append(manifest)
    return result


def generate_web(catalog: list[dict[str, object]]) -> None:
    _write(
        ROOT / "apps/web/src/generated/tool-catalog.json",
        json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
    )


def generate_python(catalog: list[dict[str, object]]) -> None:
    methods = [str(tool["slug"]).replace("-", "_") for tool in catalog]
    lines = [
        '"""Generated by scripts/generate_tool_catalog.py; do not edit."""',
        "",
        "from typing import Generic, TypeVar",
        "",
        'ToolMethod = TypeVar("ToolMethod")',
        "",
        "TOOL_METHODS = (",
        *(f'    "{method}",' for method in methods),
        ")",
        "",
        "",
        "class ToolMethods(Generic[ToolMethod]):",
        *(f"    {method}: ToolMethod" for method in methods),
        "",
    ]
    _write(
        ROOT / "sdks/python/src/multipletools/_generated_tools.py",
        "\n".join(lines),
    )


def generate_typescript(catalog: list[dict[str, object]]) -> None:
    methods = [str(tool["slug"]).replace("-", "_") for tool in catalog]
    lines = [
        "// Generated by scripts/generate_tool_catalog.py; do not edit.",
        "export const TOOL_METHODS = [",
        *(f"  '{method}'," for method in methods),
        "] as const",
        "",
    ]
    _write(
        ROOT / "sdks/typescript/src/generated-tools.ts",
        "\n".join(lines),
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--target",
        choices=("all", "web", "python", "typescript"),
        default="all",
    )
    target = parser.parse_args().target
    catalog = build_tool_catalog(manifests())
    if target in {"all", "web"}:
        generate_web(catalog)
    if target in {"all", "python"}:
        generate_python(catalog)
    if target in {"all", "typescript"}:
        generate_typescript(catalog)
    print(f"Generated {target} catalog artifacts for {len(catalog)} tools")


if __name__ == "__main__":
    main()
