"""Generated by scripts/generate_tool_catalog.py; do not edit."""

from typing import Generic, TypeVar

ToolMethod = TypeVar("ToolMethod")

TOOL_METHODS = (
    "avif_to_jpg",
    "avif_to_png",
    "avif_to_webp",
    "bmp_to_jpg",
    "bmp_to_pdf",
    "bmp_to_png",
    "compress_pdf",
    "csv_to_excel",
    "csv_to_pdf",
    "excel_to_csv",
    "excel_to_pdf",
    "heic_to_jpg",
    "heic_to_png",
    "heic_to_webp",
    "html_to_pdf",
    "html_to_word",
    "image_to_text",
    "jpg_to_avif",
    "jpg_to_bmp",
    "jpg_to_heic",
    "jpg_to_pdf",
    "jpg_to_png",
    "jpg_to_tiff",
    "jpg_to_webp",
    "markdown_to_pdf",
    "markdown_to_word",
    "pdf_to_excel",
    "pdf_to_html",
    "pdf_to_jpg",
    "pdf_to_png",
    "pdf_to_powerpoint",
    "pdf_to_text",
    "pdf_to_word",
    "png_to_avif",
    "png_to_bmp",
    "png_to_heic",
    "png_to_jpg",
    "png_to_pdf",
    "png_to_tiff",
    "png_to_webp",
    "powerpoint_to_pdf",
    "protect_pdf",
    "rotate_pdf",
    "text_to_pdf",
    "text_to_word",
    "tiff_to_jpg",
    "tiff_to_pdf",
    "tiff_to_png",
    "unlock_pdf",
    "webp_to_avif",
    "webp_to_jpg",
    "webp_to_pdf",
    "webp_to_png",
    "word_to_html",
    "word_to_pdf",
    "word_to_text",
)


class ToolMethods(Generic[ToolMethod]):
    avif_to_jpg: ToolMethod
    avif_to_png: ToolMethod
    avif_to_webp: ToolMethod
    bmp_to_jpg: ToolMethod
    bmp_to_pdf: ToolMethod
    bmp_to_png: ToolMethod
    compress_pdf: ToolMethod
    csv_to_excel: ToolMethod
    csv_to_pdf: ToolMethod
    excel_to_csv: ToolMethod
    excel_to_pdf: ToolMethod
    heic_to_jpg: ToolMethod
    heic_to_png: ToolMethod
    heic_to_webp: ToolMethod
    html_to_pdf: ToolMethod
    html_to_word: ToolMethod
    image_to_text: ToolMethod
    jpg_to_avif: ToolMethod
    jpg_to_bmp: ToolMethod
    jpg_to_heic: ToolMethod
    jpg_to_pdf: ToolMethod
    jpg_to_png: ToolMethod
    jpg_to_tiff: ToolMethod
    jpg_to_webp: ToolMethod
    markdown_to_pdf: ToolMethod
    markdown_to_word: ToolMethod
    pdf_to_excel: ToolMethod
    pdf_to_html: ToolMethod
    pdf_to_jpg: ToolMethod
    pdf_to_png: ToolMethod
    pdf_to_powerpoint: ToolMethod
    pdf_to_text: ToolMethod
    pdf_to_word: ToolMethod
    png_to_avif: ToolMethod
    png_to_bmp: ToolMethod
    png_to_heic: ToolMethod
    png_to_jpg: ToolMethod
    png_to_pdf: ToolMethod
    png_to_tiff: ToolMethod
    png_to_webp: ToolMethod
    powerpoint_to_pdf: ToolMethod
    protect_pdf: ToolMethod
    rotate_pdf: ToolMethod
    text_to_pdf: ToolMethod
    text_to_word: ToolMethod
    tiff_to_jpg: ToolMethod
    tiff_to_pdf: ToolMethod
    tiff_to_png: ToolMethod
    unlock_pdf: ToolMethod
    webp_to_avif: ToolMethod
    webp_to_jpg: ToolMethod
    webp_to_pdf: ToolMethod
    webp_to_png: ToolMethod
    word_to_html: ToolMethod
    word_to_pdf: ToolMethod
    word_to_text: ToolMethod
